[package]
name = "hecs_test"
version = "0.1.0"
authors = ["vilius"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.2.12"
rand = "*"
